### ISSUE TITLE
better iframe handling

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#398]
while #265 is super out of scope, what isn't is considering a way to help users get to those iframes in isolation. i personally open the devtools and then open the iframe url in a new window. sounds right up visbug's alley doesnt it? 

<br>

**ux:**
- hover over an iframe
- get a metatip
- `cmd + click` to open iframe in a new tab
- visbug intercepts and uses js to complete the action

<br>

**todo: (stubbed dev workflow)**
- [ ] make an iframe.js feature
- [ ] iframe feature sets up listeners for hover and click on iframes
- [ ] hover handler creates a `metatip.element` with instruction text
- [ ] click handler uses window object to make a new tab with e.target src
- [ ] import that feature from `selection.js` which initializes module? or `visbug.element`?

**Comment by adhrinae** [comment]
Is this feature guiding users to open iframe in a new tab only?

**Comment by argyleink** [comment]
that's the current scope of the feature, but you have ideas!?

**Comment by adhrinae** [comment]
Not really. Just to clarify my understanding 😅.
This is a good enough feature. I wondered I couldn't get any responses from the visbug when I tried to use it on an iframe.

I'd like to grab this issue but it might take some time.

**Comment by argyleink** [comment]
agreed selectable is too big! iframe could be a good tool to start a new pattern? i'm open to thoughts around a `selectable.js` refactor

**Comment by adhrinae** [comment]
@argyleink I'm taking too long time to implement this feature 😞 because I couldn't look into this project recently. my bad.

There was some progress. I've managed to show the tip when hovering on an iframe element.

<img width="1072" alt="Screen Shot 2019-12-08 at 22 02 20" src="https://user-images.githubusercontent.com/14539203/70389752-f291f880-1a06-11ea-8985-cca2ca09b6bb.png">

(And making the inception of Visbug website didn't work well, so I'm using a youtube embedded video for the local development.)

The biggest problem is there's no `MouseEvent` for an iframe element.
We can only bind `blur` event on `window`  to detect iframe when the click event happens.

Reference: https://gist.github.com/jaydson/1780598

So I'm thinking to create **additional custom element** on top of an iframe element with the same width and height, then to bind a click event that custom element.
Perhaps that custom element should have a slightly dark background like `rgba(0, 0, 0, 0.6)`.

### Things need to be done (maybe)
- [ ] a new custom element to wrap an iframe element.
- [ ] prevent to show the tooltip when `MetaTip` or `A11y` tool is selected.

**Comment by argyleink** [comment]
Thanks for this comment and check-in! Here's some of my thoughts and feedback 🙂

- i should have remembered that clicks on iframes wasn't going to be a thing we could leverage, it's one of the reasons visbug can't operate on an iframe to begin with. sorry for not alerting you earlier, i was also oblivious to it when i write the prelim idea on how to tackle this. thanks for calling it out explicitly.
- good news is that the hover event can currently see iframes and could definitely delegate the creation of a click stealing overlay to an iframe capture handler. that's a great idea. perhaps the tooltip is replaced by a meaningful overlay? so we put the messaging into the overlay, and if they click while the overlay is showing, we send them to the iframe destination? 

![Screen Shot 2019-12-09 at 11 55 56 AM](https://user-images.githubusercontent.com/1134620/70468347-c9f81600-1a7b-11ea-9ee7-0f1a40502d77.png)

that would update the flow to this:
- hover over an iframe
- create an overlay (if not already created) with a message about what happens with they click
- click opens the iframe in a new tab
- hover out, set created overlay opacity to display none (or whatever works best here, tbd). maybe since an iframe wont have a hoverout we leverage `clearHover()`? 

this is still a great addition to visbug!

**Comment by adhrinae** [comment]
Yes, Overlay! I completely forgot that term.
That's for the advice. I'll try to approach this problem from creating overlay.
