### ISSUE TITLE
Meta tip: ability to show just local changes

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#54]
a toggle somewhere would be nice to help the share be succinct

**Comment by argyleink** [comment]
this pseudo works today, but needs love:
- [ ] needs to know the difference between inline styles and visbug applied styles
- [ ] needs to feature "export to [gallery,drive,dropbox,cloud,etc]" button for **designers**
- [ ] needs to feature "copy as [css,scss,etc]" button for **developers**
- [ ] should support a global registry so all changes can be exported at once, see #199 
- [ ] should still show changes contextual to the element
- [ ] should allow toggling all visbug changes on/off

very worthwhile and critical features, and much of it needs some foundational work and deep integrated features in order to be completed properly. ping this thread if you're looking to take it on and i can articulate some of the scaffolding needed. 

also, if you have additional feature requests, make them, and i can update this list

**Comment by argyleink** [comment]
wonder if "changes" should even be a mode? 
with hotkeys (for replay) and maybe some other fun stuff? seems like there's enough of a purpose for it that i'd like to see it stop piggybacking off of the style inspector. 
thoughts?

**Comment by jaminroe** [comment]
I was also looking for something in this extension, that shows me a list of CSS rules that I've modified. Otherwise, I don't see much value in this extension at all. Doesn't make it useable.

I prefer [StyleURL extension](https://www.styleurl.app) for now, until this improvement is made. Check it out. They have a stylesheet panel that you can open, that shows the local changes you've made.

**Comment by argyleink** [comment]
continue using styleURL, it's a very neat tool I'm surprised more folks don't use. it's for a different audience though, one that knows how to code and use the devtools. visbug doesnt require that knowledge.
